[package]
name = "rust_starter"
version = "0.1.0"
authors = ["Team Fernish"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.103"
serde_json = "1.0.42"
